services:
  jupyterhub:
    build: .
    image: my-jupyterhub
    container_name: jupyterhub
    ports:
      - "8000:8000"
    volumes:
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - ./pre_spawn.py:/srv/jupyterhub/pre_spawn.py
      - jupyterhub-data:/srv/jupyterhub
      - jupyterhub-home:/home   # ⭐ 關鍵這行
    command: jupyterhub -f /srv/jupyterhub/jupyterhub_config.py
    restart: always

volumes:
  jupyterhub-data:
  jupyterhub-home:
